In [74]:
import numpy as np

In [75]:
# define training data

X = np.array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]]) # training inputs
y = np.array([[0,1,1,0]]).T # training outputs/labels

In [76]:
print(X)

[[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]


In [77]:
print(y)

[[0]
 [1]
 [1]
 [0]]


In [78]:
num_features = len(X[0])
num_output = len(y[0])

In [79]:
print(num_features, num_output)

3 1


In [85]:
class NeuralNetwork():
    
    def __init__(self, inputs, labels, epochs=10000):
        
        self.X = inputs
        self.y = labels
        self.num_features = len(inputs[0])
        self.num_output = len(labels[0])
        self.epochs = epochs
        np.random.seed(1)
        
        # initialize weights with a mean of 0
        self.weights = 2*np.random.random((num_features,num_output))-1
        self.gradients = None
        
    def sigmoid(self, weighted_input):
        return 1/(1+np.exp(-weighted_input))
    
    def sigmoid_derivative(self, output):
        
        # the derivative of a sigmoid function can be calculated
        # using its output, so output refers to output of the
        # sigmoid activation
        # returns the slope of each point in output
        
        return output*(1-output)
        
    def train(self):
        
        for i in range(self.epochs): # train for number of epochs
            
            layer0 = self.X # first layer in network or input data
            
            layer1 = self.sigmoid(np.dot(layer0, self.weights))  # second layer which is also output layer in this case
            
            layer1_error = y - layer1  # calculate error at the layer
            
            # multiply error by slope of sigmoid at the values in layer1
            # using the Error Weighted Derivative
            layer1_delta = layer1_error * self.sigmoid_derivative(layer1)
            
            self.gradients = np.dot(self.X.T, layer1_delta)
        
            self.weights = self.weights + self.gradients
            
    def predict(self, input):
        
        return self.sigmoid(np.dot(input, self.weights))
        

In [86]:
nn = NeuralNetwork(X, y)

In [87]:
nn.train()

In [88]:
nn.predict([1,0,0])

array([ 0.99993704])

In [89]:
nn.predict([0,0,0])

array([ 0.5])

In [90]:
nn.predict([0,0,1])

array([ 0.009664])

In [91]:
nn.weights

array([[ 9.67299303],
       [-0.2078435 ],
       [-4.62963669]])

In [92]:
nn.gradients.shape

(3, 1)

In [93]:
nn.sigmoid_derivative(y).shape

(4, 1)