##### Copyright 2019 The TensorFlow Authors. [Licensed under the Apache License, Version 2.0](#scrollTo=y_UVSRtBBsJk).

In [0]:
#@title Licensed under the Apache License, Version 2.0 (the "License"); { display-mode: "form" }
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

## **Introduction to Colab and Swift**

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/drive/119Cn14ku8ksgaRNKF1zI3z9UiKfnYrP2"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="Link to be updated"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />GitHub link to be updated accordingly</a>
  </td>
</table>

Welcome to this notebook where you will get a quick introduction to the Swift programming language and the environment used for the course's exercises: Colab.

Colab is a Python + Swift development environment that runs in the browser using Google Cloud. 

For example, to print "Hello World", just hover the mouse over [  ] and press the play button to the upper left. Or press shift-enter to execute.

In [0]:
import TensorFlow

import Python

In [3]:
print("Hello, world!")

Hello, world!


## Functions, Conditionals, and Iteration
Let's create a Swift function, and call it from a loop.

In [4]:
func helloWorld(x: Int, y: Int) -> Int {
    if x < 10 {
        print("Hello World, x was < 10")
    } else if x < 20 {
        print("Hello World, x was >= 10 but < 20")
    } else {
        print("Hello World, x was >= 20")
    }
  return x + y
}

for i in stride(from: 8, to: 25, by: 5) {
    print("--- Now running with i: \(i)")
    var r = helloWorld(x: i, y: i)
    print("Result from helloWorld: \(String(r))")
}

--- Now running with i: 8
Hello World, x was < 10
Result from helloWorld: 16
--- Now running with i: 13
Hello World, x was >= 10 but < 20
Result from helloWorld: 26
--- Now running with i: 18
Hello World, x was >= 10 but < 20
Result from helloWorld: 36
--- Now running with i: 23
Hello World, x was >= 20
Result from helloWorld: 46


In [5]:
print(helloWorld(x: 1, y: 2))

Hello World, x was < 10
3


Easy, right?

If you want a loop starting at 0 to 2 (exclusive) you could do any of the following

In [6]:
print("Iterate over the items. `0..<2` is like a list [0, 1].")
for i in 0..<2 {
  print(i)
}

print("Iterate over an actual list.")
for i in [0, 1] {
  print(i)
}

print("While works")
var i = 0
while i < 2 {
  print(i)
  i += 1
}

Iterate over the items. `0..<2` is like a list [0, 1].
0
1
Iterate over an actual list.
0
1
While works
0
1


In [7]:
print("Swift supports standard key words like continue and break")
while true {
  print("Entered while")
  break
}

Swift supports standard key words like continue and break
Entered while


## NumPy and lists
Use Python.import to import a Python module. It works like the import keyword in Python.

Swift For TensorFlow supports Python interoperability.
You can import Python modules from Swift, call Python functions, and convert values between Swift and Python.

Python has lists built into the language.
However, we will use a library called NumPy for this.
Numpy gives you lots of support functions that are useful when doing machine learning.

In the following, you will see an import statement that makes the entire NumPy package available to Swift for TensorFlow. By assigning this imported library to np, we can access NumPy symbols using an abbreviated syntax.

In [8]:
let np = Python.import("numpy")  // Make NumPy available using np.

var a = np.array(["Hello", "World"])
a = np.append(a, "!")
print("Current array: \(a)")
print("Printing each element" )
for i in a {
  print(i)
}

print("\nPrinting each element and their index")

for (i, e) in a.enumerated() {
    print("Index: \(i), was: \(e)")
}


Current array: ['Hello' 'World' '!']
Printing each element
Hello
World
!

Printing each element and their index
Index: 0, was: Hello
Index: 1, was: World
Index: 2, was: !


In [9]:
print("Showing some basic math on arrays")
var b = np.array([0, 1, 4, 3, 2])
print("Max: \(np.max(b))")
print("Average: \(np.average(b))")
print("Max Index: \(np.argmax(b))")

Showing some basic math on arrays
Max: 4
Average: 2.0
Max Index: 2


In Swift, PythonObject represents an object from Python. All Python APIs use and return PythonObject instances.

Basic types in Swift (like numbers and arrays) are convertible to PythonObject. In some cases (for literals and functions taking PythonConvertible arguments), conversion happens implicitly. To explicitly cast a Swift value to PythonObject, use the PythonObject initializer.

PythonObject defines many standard operations, including numeric operations, indexing, and iteration.

In [10]:
print("You can print the type of anything")
print("Swift type")
print("Type of b: \(type(of: b)), type of b[0]: \(type(of: b[0]))")
print("Python type")
print("Type of b: \(Python.type(b)), type of b[0]: \(Python.type(b[0]))")

You can print the type of anything
Swift type
Type of b: PythonObject, type of b[0]: PythonObject
Python type
Type of b: <class 'numpy.ndarray'>, type of b[0]: <class 'numpy.int64'>


In [11]:
print("Use NumPy to create a [3, 3] dimension array by random numbers")
var c = np.random.rand(3, 3)
print(c)

Use NumPy to create a [3, 3] dimension array by random numbers
[[0.37558794 0.76188537 0.64058941]
 [0.61845844 0.7878529  0.42337332]
 [0.53637738 0.67752177 0.07434855]]


In [12]:
print("You can print the dimensions of arrays")
print("Shape of a: \(a.shape)")
print("Shape of b: \(b.shape)")
print("Shape of c: \(c.shape)")

You can print the dimensions of arrays
Shape of a: (3,)
Shape of b: (5,)
Shape of c: (3, 3)


All usage of Colab in this course is completely free of charge. Even GPU usage in Colab is provided free of charge for up to several hours of execution every day.

**Using GPUs**
* Many of the exercises in this course execute faster when using the GPU runtime. To enable, select Runtime | Change runtime type | Hardware accelerator | GPU

**Some final words on Colab**
*   You execute each cell in order, you can edit & re-execute cells if you want.
*   Sometimes, this could have unintended consequences. For example, if you add a dimension to an array and execute the cell multiple times, the cells that follow may not work. If you encounter problems, reset your environment:
  *   Runtime -> Restart runtime... Resets your Python shell
  *   Runtime -> Restart all runtimes... Will reset the Colab image, and get you back to a 100% clean environment
* You can also clear the output in the Colab by doing: Edit -> Clear all outputs
* Colabs in this course are loaded from GitHub. Save to your Google Drive if you want a copy with your code/output: File -> Save a copy in Drive...

**Learn More**
*   Check out [this](https://www.youtube.com/watch?v=inN8seMm7UI&list=PLQY2H8rRoyvwLbzbnKJ59NkZvQAW9wLbx&index=3) episode of #CodingTensorFlow, and don't forget to subscribe to the YouTube channel ;)
