In [7]:
import numpy as np

In [8]:
list1 = [0,1,2,3,4]

In [10]:
list1

[0, 1, 2, 3, 4]

In [11]:
arr1d = np.array(list1)

In [12]:
arr1d

array([0, 1, 2, 3, 4])

In [13]:
list1.append(5)

In [14]:
list1

[0, 1, 2, 3, 4, 5]

In [15]:
list1 + 2

TypeError: can only concatenate list (not "int") to list

In [16]:
arr1d + 2

array([2, 3, 4, 5, 6])

In [17]:
list2 = [[1, 1, 1], [2, 2 ,2], [3, 3, 3]]
arr2d = np.array(list2)

In [19]:
type(arr2d)

numpy.ndarray

In [20]:
arr2d.dtype

dtype('int32')

In [21]:
arr2d = np.array(list2, dtype = 'float')

In [22]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [25]:
arr2d = arr2d.astype('int')

In [26]:
arr2d.astype('str')

array([['1', '1', '1'],
       ['2', '2', '2'],
       ['3', '3', '3']], dtype='<U11')

In [30]:
list1.append('6')

In [31]:
list1

[0, 1, 2, 3, 4, 5, '6']

In [32]:
np2list = arr2d.tolist()

In [33]:
np2list

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [34]:
arr2d.tostring()

b'\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00'

In [35]:
arr2d.tobytes()

b'\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00'

# dtype and shape

In [36]:
list2

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [38]:
arr2d = arr2d.astype('float' )

In [39]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [40]:
print('Shape: ', arr2d.shape) # python3


Shape:  (3, 3)


In [41]:
arr2d.dtype

dtype('float64')

In [43]:
arr2d.size

9

In [44]:
arr1d.size

5

In [45]:
arr2d.ndim

2

In [46]:
arr1d.ndim

1

In [50]:
arr1d = arr1d * arr1d

In [51]:
arr1d

array([ 4,  9,  0,  1, 36], dtype=int32)

In [55]:
arr1d[1]

9

In [60]:
arr2d[1][0] #[R][C]

2.0

In [59]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [61]:
boolarr = arr2d<3

In [62]:
boolarr

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [63]:
arr2d[boolarr]

array([1., 1., 1., 2., 2., 2.])

In [64]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [65]:
arr2d[::-1, ]

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [66]:
arr2d[::-1, ::-1]

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

## np.nan, np.inf

In [67]:
np.nan

nan

In [68]:
np.inf

inf

In [69]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [70]:
arr2d[0][0] = np.nan
arr2d[0][1] = np.inf
arr2d

array([[nan, inf,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [71]:
np.isnan(arr2d)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [72]:
np.isinf(arr2d)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [73]:
missing_flag = np.isnan(arr2d) | np.isinf(arr2d)
missing_flag

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [74]:
#replace inf and nan with 0

In [75]:
arr2d[missing_flag]

array([nan, inf])

In [76]:
arr2d[missing_flag] = 0

In [77]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

# Statistical operations

In [78]:
#mean, std, var

In [79]:
arr2d.mean()

1.7777777777777777

In [80]:
arr2d.max()

3.0

In [81]:
arr2d.min()

0.0

In [82]:
arr2d.std()

1.1331154474650633

In [83]:
arr2d.var()

1.2839506172839505

In [85]:
arr2d.squeeze()

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [86]:
arr2d.cumsum()

array([ 0.,  0.,  1.,  3.,  5.,  7., 10., 13., 16.])

In [87]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [88]:
arr = arr2d[:2, :2]

In [89]:
arr

array([[0., 0.],
       [2., 2.]])

In [91]:
arr2d[1:3, 1:2]

array([[2.],
       [3.]])

In [92]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [101]:
a = arr2d.reshape(1,9)
a

array([[0., 0., 1., 2., 2., 2., 3., 3., 3.]])

In [100]:
a.ndim

2

In [95]:
arr2d.reshape(9,1)

array([[0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.]])

In [105]:
a = arr2d.flatten()
a #copy

array([0., 0., 1., 2., 2., 2., 3., 3., 3.])

In [106]:
b = arr2d.ravel()
b #reference

array([0., 0., 1., 2., 2., 2., 3., 3., 3.])

In [107]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [109]:
b[0] = -1

In [110]:
arr2d

array([[-1.,  0.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

# sequence, repetitions, and random numbers 

In [116]:
np.arange(1, 5, dtype = 'int')

array([1, 2, 3, 4])

In [118]:
np.arange(1, 50, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [123]:
np.linspace(1, 50, 9)

array([ 1.   ,  7.125, 13.25 , 19.375, 25.5  , 31.625, 37.75 , 43.875,
       50.   ])

In [124]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [126]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [127]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [128]:
a = [1, 2, 3]

In [129]:
a

[1, 2, 3]

In [130]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [131]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [132]:
np.repeat(arr2d, 3)

array([-1., -1., -1.,  0.,  0.,  0.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.])

In [133]:
arr2d

array([[-1.,  0.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [139]:
np.random.rand(3, 3)

array([[0.03022941, 0.4897838 , 0.48808364],
       [0.06658789, 0.25569082, 0.30411541],
       [0.65788261, 0.16300932, 0.61885932]])

In [138]:
np.random.randn(3, 3)

array([[-0.95832052, -0.33374875,  0.46566206],
       [-1.04891141,  0.5784687 , -0.1718599 ],
       [ 0.27468945, -0.93154267,  0.65645431]])

In [141]:
np.random.randint(0, 10, [3,3])

array([[6, 4, 0],
       [2, 5, 9],
       [7, 3, 0]])

In [157]:
np.random.seed(1)
np.random.randint(0, 10, [3,3])

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [161]:
np.unique(arr2d)

array([-1.,  0.,  1.,  2.,  3.])

In [162]:
arr2d

array([[-1.,  0.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [163]:
uniques, counts = np.unique(arr2d, return_counts= True)

In [164]:
uniques

array([-1.,  0.,  1.,  2.,  3.])

In [165]:
counts

array([1, 1, 1, 3, 3], dtype=int64)

# Numpy Crash Course Part 2 

In [166]:
arr = np.array([8,94,8,56,1,3,4,5,7])
print(arr)

[ 8 94  8 56  1  3  4  5  7]


In [167]:
index_gt10 = np.where(arr>10)
index_gt10

(array([1, 3], dtype=int64),)

In [168]:
arr[index_gt10]

array([94, 56])

In [169]:
arr[arr>10]

array([94, 56])

In [170]:
arr>10

array([False,  True, False,  True, False, False, False, False, False])

In [171]:
np.where(arr>10, 'gt10', 'lt10')

array(['lt10', 'gt10', 'lt10', 'gt10', 'lt10', 'lt10', 'lt10', 'lt10',
       'lt10'], dtype='<U4')

In [172]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [173]:
arr.max()

94

In [174]:
arr.argmax()

1

In [176]:
arr[arr.argmin()]

1

In [177]:
arr.argmin()

4

## read and write csv file 

In [ ]:
#np.genfromtxt(), np.loadtxt()

In [181]:
data = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv', delimiter= ',', skip_header= 1, 
              filling_values= -1000, dtype = 'float')

In [184]:
data.shape

(392, 9)

In [186]:
np.set_printoptions(suppress=True)
data[:3]

array([[   18. ,     8. ,   307. ,   130. ,  3504. ,    12. ,    70. ,
            1. , -1000. ],
       [   15. ,     8. ,   350. ,   165. ,  3693. ,    11.5,    70. ,
            1. , -1000. ],
       [   18. ,     8. ,   318. ,   150. ,  3436. ,    11. ,    70. ,
            1. , -1000. ]])

In [199]:
data2 = np.genfromtxt('https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv', delimiter=',', skip_header=1, dtype= None)
data2[:3]

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


array([(18., 8, 307., 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15., 8, 350., 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18., 8, 318., 150, 3436, 11. , 70, 1, b'"plymouth satellite"')],
      dtype=[('f0', '<f8'), ('f1', '<i4'), ('f2', '<f8'), ('f3', '<i4'), ('f4', '<i4'), ('f5', '<f8'), ('f6', '<i4'), ('f7', '<i4'), ('f8', 'S38')])

In [200]:
np.savetxt('data.csv', data, delimiter=',')

In [201]:
data

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [202]:
np.save('data.npy', data)

In [203]:
np.savez('data2.npz', data, data2)

In [204]:
d = np.load('data.npy')
d

array([[   18.,     8.,   307., ...,    70.,     1., -1000.],
       [   15.,     8.,   350., ...,    70.,     1., -1000.],
       [   18.,     8.,   318., ...,    70.,     1., -1000.],
       ...,
       [   32.,     4.,   135., ...,    82.,     1., -1000.],
       [   28.,     4.,   120., ...,    82.,     1., -1000.],
       [   31.,     4.,   119., ...,    82.,     1., -1000.]])

In [206]:
d2 = np.load('data2.npz')

In [208]:
d2.files

['arr_0', 'arr_1']

In [210]:
d2['arr_1']

array([(18. , 8, 307. , 130, 3504, 12. , 70, 1, b'"chevrolet chevelle malibu"'),
       (15. , 8, 350. , 165, 3693, 11.5, 70, 1, b'"buick skylark 320"'),
       (18. , 8, 318. , 150, 3436, 11. , 70, 1, b'"plymouth satellite"'),
       (16. , 8, 304. , 150, 3433, 12. , 70, 1, b'"amc rebel sst"'),
       (17. , 8, 302. , 140, 3449, 10.5, 70, 1, b'"ford torino"'),
       (15. , 8, 429. , 198, 4341, 10. , 70, 1, b'"ford galaxie 500"'),
       (14. , 8, 454. , 220, 4354,  9. , 70, 1, b'"chevrolet impala"'),
       (14. , 8, 440. , 215, 4312,  8.5, 70, 1, b'"plymouth fury iii"'),
       (14. , 8, 455. , 225, 4425, 10. , 70, 1, b'"pontiac catalina"'),
       (15. , 8, 390. , 190, 3850,  8.5, 70, 1, b'"amc ambassador dpl"'),
       (15. , 8, 383. , 170, 3563, 10. , 70, 1, b'"dodge challenger se"'),
       (14. , 8, 340. , 160, 3609,  8. , 70, 1, b'"plymouth \'cuda 340"'),
       (15. , 8, 400. , 150, 3761,  9.5, 70, 1, b'"chevrolet monte carlo"'),
       (14. , 8, 455. , 225, 3086, 10. , 70, 1

##  concat with row and col wise

In [211]:
arr1 = np.zeros([4, 4])
arr2 = np.ones([4, 4])

In [212]:
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [213]:
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [214]:
#np.concatenate, np.vstack, np.r_

In [219]:
np.concatenate([arr1, arr2], axis = 0)
np.vstack([arr1, arr2])
np.r_[arr1, arr2]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [220]:
np.concatenate([arr1, arr2], axis = 1)

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [221]:
np.hstack([arr1, arr2])

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [222]:
np.c_[arr1, arr2]

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

## sort a numpy array 

In [223]:
arr = np.random.randint(1, 10, size = [10, 5])

In [224]:
arr

array([[3, 5, 6, 3, 5],
       [3, 5, 8, 8, 2],
       [8, 1, 7, 8, 7],
       [2, 1, 2, 9, 9],
       [4, 9, 8, 4, 7],
       [6, 2, 4, 5, 9],
       [2, 5, 1, 4, 3],
       [1, 5, 3, 8, 8],
       [9, 7, 4, 8, 8],
       [5, 6, 4, 7, 9]])

In [226]:
np.sort(arr, axis = 0)

array([[1, 1, 1, 3, 2],
       [2, 1, 2, 4, 3],
       [2, 2, 3, 4, 5],
       [3, 5, 4, 5, 7],
       [3, 5, 4, 7, 7],
       [4, 5, 4, 8, 8],
       [5, 5, 6, 8, 8],
       [6, 6, 7, 8, 9],
       [8, 7, 8, 8, 9],
       [9, 9, 8, 9, 9]])

In [230]:
sorted_index = arr[:, 0].argsort()

In [231]:
arr[sorted_index]

array([[1, 5, 3, 8, 8],
       [2, 1, 2, 9, 9],
       [2, 5, 1, 4, 3],
       [3, 5, 6, 3, 5],
       [3, 5, 8, 8, 2],
       [4, 9, 8, 4, 7],
       [5, 6, 4, 7, 9],
       [6, 2, 4, 5, 9],
       [8, 1, 7, 8, 7],
       [9, 7, 4, 8, 8]])

In [232]:
arr

array([[3, 5, 6, 3, 5],
       [3, 5, 8, 8, 2],
       [8, 1, 7, 8, 7],
       [2, 1, 2, 9, 9],
       [4, 9, 8, 4, 7],
       [6, 2, 4, 5, 9],
       [2, 5, 1, 4, 3],
       [1, 5, 3, 8, 8],
       [9, 7, 4, 8, 8],
       [5, 6, 4, 7, 9]])

# working with dates

In [235]:
d = np.datetime64('2019-06-02 23:10:00')

In [236]:
d

numpy.datetime64('2019-06-02T23:10:00')

In [240]:
d + 1000

numpy.datetime64('2019-06-02T23:26:40')

In [241]:
16*60+40

1000

In [243]:
oneday = np.timedelta64(1, 'D')

In [244]:
oneday

numpy.timedelta64(1,'D')

In [245]:
d + oneday

numpy.datetime64('2019-06-03T23:10:00')

In [246]:
oneminute = np.timedelta64(1, 'm')

In [247]:
d + oneminute

numpy.datetime64('2019-06-02T23:11:00')

In [249]:
dates = np.arange(np.datetime64('2019-06-02'), np.datetime64('2020-06-02'), 2)
dates

array(['2019-06-02', '2019-06-04', '2019-06-06', '2019-06-08',
       '2019-06-10', '2019-06-12', '2019-06-14', '2019-06-16',
       '2019-06-18', '2019-06-20', '2019-06-22', '2019-06-24',
       '2019-06-26', '2019-06-28', '2019-06-30', '2019-07-02',
       '2019-07-04', '2019-07-06', '2019-07-08', '2019-07-10',
       '2019-07-12', '2019-07-14', '2019-07-16', '2019-07-18',
       '2019-07-20', '2019-07-22', '2019-07-24', '2019-07-26',
       '2019-07-28', '2019-07-30', '2019-08-01', '2019-08-03',
       '2019-08-05', '2019-08-07', '2019-08-09', '2019-08-11',
       '2019-08-13', '2019-08-15', '2019-08-17', '2019-08-19',
       '2019-08-21', '2019-08-23', '2019-08-25', '2019-08-27',
       '2019-08-29', '2019-08-31', '2019-09-02', '2019-09-04',
       '2019-09-06', '2019-09-08', '2019-09-10', '2019-09-12',
       '2019-09-14', '2019-09-16', '2019-09-18', '2019-09-20',
       '2019-09-22', '2019-09-24', '2019-09-26', '2019-09-28',
       '2019-09-30', '2019-10-02', '2019-10-04', '2019-

## Numpy Advanced Function

In [250]:
#vectorize()

In [252]:
def foo(x):
    if x%2 == 1:
        return x**2
    else:
        return x/2

foo(11)

121

In [253]:
foo_v = np.vectorize(foo, otypes=[float])


In [254]:
arr

array([[3, 5, 6, 3, 5],
       [3, 5, 8, 8, 2],
       [8, 1, 7, 8, 7],
       [2, 1, 2, 9, 9],
       [4, 9, 8, 4, 7],
       [6, 2, 4, 5, 9],
       [2, 5, 1, 4, 3],
       [1, 5, 3, 8, 8],
       [9, 7, 4, 8, 8],
       [5, 6, 4, 7, 9]])

In [255]:
foo_v(arr)

array([[ 9., 25.,  3.,  9., 25.],
       [ 9., 25.,  4.,  4.,  1.],
       [ 4.,  1., 49.,  4., 49.],
       [ 1.,  1.,  1., 81., 81.],
       [ 2., 81.,  4.,  2., 49.],
       [ 3.,  1.,  2., 25., 81.],
       [ 1., 25.,  1.,  2.,  9.],
       [ 1., 25.,  9.,  4.,  4.],
       [81., 49.,  2.,  4.,  4.],
       [25.,  3.,  2., 49., 81.]])