In [1]:
import gym
import numpy as np

In [2]:
# load the environment

env = gym.make('FrozenLake-v0')


[2017-05-14 14:46:41,383] Making new env: FrozenLake-v0


In [3]:
env.action_space

Discrete(4)

In [4]:
env.observation_space

Discrete(16)

In [5]:
# implement q-table learning

Q = np.zeros([env.observation_space.n, env.action_space.n]) #16x4 table - states in rows, actions in cols

lr = .85
y = 0.99 # discount rate for future rewards
num_episodes = 2000

# list to contain total rewards and steps per episode
rList= []

for i in range(num_episodes):
    # reset env and get new obs
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    
    # the q-table learning algo
    while j<99:
        j+=1
        # choose an action greedily from q table
        a = np.argmax(Q[s,:] + np.random.randn(1, env.action_space.n)*(1./(i+1)))
        # getnew state and reward
        s1, r, d, _ = env.step(a)
        # update q-table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r+ y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    rList.append(rAll)

In [6]:
print("Score over time", str(sum(rList)/num_episodes))

Score over time 0.5385


In [8]:
print("Final Q table values")
print(Q)

Final Q table values
[[  7.18127708e-01   3.18613399e-02   2.79450837e-02   2.00133060e-02]
 [  6.41317621e-05   4.19388414e-03   3.03648979e-03   5.22126056e-01]
 [  1.71846678e-02   1.88044778e-03   3.02366034e-03   4.79107324e-01]
 [  2.38530523e-03   6.30291660e-03   1.56434156e-03   3.55779497e-01]
 [  5.35330041e-01   1.66309692e-03   4.71846154e-04   3.76871851e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  6.45216771e-04   2.87412301e-05   4.82837945e-01   3.57422067e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.24529502e-03   2.01079942e-03   1.65550221e-03   6.99178905e-01]
 [  4.00908868e-04   8.51324958e-01   9.68241682e-04   0.00000000e+00]
 [  8.89350167e-01   4.02069646e-04   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.58965535e-04   1.90593955e-03   7.77741427e-01   0

In [9]:
import matplotlib.pyplot as plt
%matplotlib inline

In [13]:
env.render(mode='human')

  (Up)
SFFF
FHFH
FFFH
HFFG


In [59]:
print(np.argmax(Q, axis=1))

[0 3 3 3 0 0 2 0 3 1 0 0 0 2 3 0]


In [27]:
print(rList[0],rList[200], rList[-1])

0.0 1.0 1.0


In [54]:
t = env.reset()

In [55]:
t

0

In [56]:
u = env.step(2)

In [57]:
u

(1, 0.0, False, {'prob': 0.3333333333333333})

NameError: name 'tf' is not defined