In [7]:
import numpy as np

In [8]:
list1 = [0,1,2,3,4]

In [10]:
list1

[0, 1, 2, 3, 4]

In [11]:
arr1d = np.array(list1)

In [12]:
arr1d

array([0, 1, 2, 3, 4])

In [13]:
list1.append(5)

In [14]:
list1

[0, 1, 2, 3, 4, 5]

In [15]:
list1 + 2

TypeError: can only concatenate list (not "int") to list

In [16]:
arr1d + 2

array([2, 3, 4, 5, 6])

In [17]:
list2 = [[1, 1, 1], [2, 2 ,2], [3, 3, 3]]
arr2d = np.array(list2)

In [19]:
type(arr2d)

numpy.ndarray

In [20]:
arr2d.dtype

dtype('int32')

In [21]:
arr2d = np.array(list2, dtype = 'float')

In [22]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [25]:
arr2d = arr2d.astype('int')

In [26]:
arr2d.astype('str')

array([['1', '1', '1'],
       ['2', '2', '2'],
       ['3', '3', '3']], dtype='<U11')

In [30]:
list1.append('6')

In [31]:
list1

[0, 1, 2, 3, 4, 5, '6']

In [32]:
np2list = arr2d.tolist()

In [33]:
np2list

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [34]:
arr2d.tostring()

b'\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00'

In [35]:
arr2d.tobytes()

b'\x01\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00\x03\x00\x00\x00'

# dtype and shape

In [36]:
list2

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]

In [38]:
arr2d = arr2d.astype('float' )

In [39]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [40]:
print('Shape: ', arr2d.shape) # python3


Shape:  (3, 3)


In [41]:
arr2d.dtype

dtype('float64')

In [43]:
arr2d.size

9

In [44]:
arr1d.size

5

In [45]:
arr2d.ndim

2

In [46]:
arr1d.ndim

1

In [50]:
arr1d = arr1d * arr1d

In [51]:
arr1d

array([ 4,  9,  0,  1, 36], dtype=int32)

In [55]:
arr1d[1]

9

In [60]:
arr2d[1][0] #[R][C]

2.0

In [59]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [61]:
boolarr = arr2d<3

In [62]:
boolarr

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [63]:
arr2d[boolarr]

array([1., 1., 1., 2., 2., 2.])

In [64]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [65]:
arr2d[::-1, ]

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [66]:
arr2d[::-1, ::-1]

array([[3., 3., 3.],
       [2., 2., 2.],
       [1., 1., 1.]])

## np.nan, np.inf

In [67]:
np.nan

nan

In [68]:
np.inf

inf

In [69]:
arr2d

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [70]:
arr2d[0][0] = np.nan
arr2d[0][1] = np.inf
arr2d

array([[nan, inf,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [71]:
np.isnan(arr2d)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [72]:
np.isinf(arr2d)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [73]:
missing_flag = np.isnan(arr2d) | np.isinf(arr2d)
missing_flag

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [74]:
#replace inf and nan with 0

In [75]:
arr2d[missing_flag]

array([nan, inf])

In [76]:
arr2d[missing_flag] = 0

In [77]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

# Statistical operations

In [78]:
#mean, std, var

In [79]:
arr2d.mean()

1.7777777777777777

In [80]:
arr2d.max()

3.0

In [81]:
arr2d.min()

0.0

In [82]:
arr2d.std()

1.1331154474650633

In [83]:
arr2d.var()

1.2839506172839505

In [85]:
arr2d.squeeze()

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [86]:
arr2d.cumsum()

array([ 0.,  0.,  1.,  3.,  5.,  7., 10., 13., 16.])

In [87]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [88]:
arr = arr2d[:2, :2]

In [89]:
arr

array([[0., 0.],
       [2., 2.]])

In [91]:
arr2d[1:3, 1:2]

array([[2.],
       [3.]])

In [92]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [101]:
a = arr2d.reshape(1,9)
a

array([[0., 0., 1., 2., 2., 2., 3., 3., 3.]])

In [100]:
a.ndim

2

In [95]:
arr2d.reshape(9,1)

array([[0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [2.],
       [3.],
       [3.],
       [3.]])

In [105]:
a = arr2d.flatten()
a #copy

array([0., 0., 1., 2., 2., 2., 3., 3., 3.])

In [106]:
b = arr2d.ravel()
b #reference

array([0., 0., 1., 2., 2., 2., 3., 3., 3.])

In [107]:
arr2d

array([[0., 0., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [109]:
b[0] = -1

In [110]:
arr2d

array([[-1.,  0.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

# sequence, repetitions, and random numbers 

In [116]:
np.arange(1, 5, dtype = 'int')

array([1, 2, 3, 4])

In [118]:
np.arange(1, 50, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [123]:
np.linspace(1, 50, 9)

array([ 1.   ,  7.125, 13.25 , 19.375, 25.5  , 31.625, 37.75 , 43.875,
       50.   ])

In [124]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [126]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [127]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [128]:
a = [1, 2, 3]

In [129]:
a

[1, 2, 3]

In [130]:
np.tile(a, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [131]:
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [132]:
np.repeat(arr2d, 3)

array([-1., -1., -1.,  0.,  0.,  0.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.])

In [133]:
arr2d

array([[-1.,  0.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [139]:
np.random.rand(3, 3)

array([[0.03022941, 0.4897838 , 0.48808364],
       [0.06658789, 0.25569082, 0.30411541],
       [0.65788261, 0.16300932, 0.61885932]])

In [138]:
np.random.randn(3, 3)

array([[-0.95832052, -0.33374875,  0.46566206],
       [-1.04891141,  0.5784687 , -0.1718599 ],
       [ 0.27468945, -0.93154267,  0.65645431]])

In [141]:
np.random.randint(0, 10, [3,3])

array([[6, 4, 0],
       [2, 5, 9],
       [7, 3, 0]])

In [157]:
np.random.seed(1)
np.random.randint(0, 10, [3,3])

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [161]:
np.unique(arr2d)

array([-1.,  0.,  1.,  2.,  3.])

In [162]:
arr2d

array([[-1.,  0.,  1.],
       [ 2.,  2.,  2.],
       [ 3.,  3.,  3.]])

In [163]:
uniques, counts = np.unique(arr2d, return_counts= True)

In [164]:
uniques

array([-1.,  0.,  1.,  2.,  3.])

In [165]:
counts

array([1, 1, 1, 3, 3], dtype=int64)