In [2]:
from __future__ import print_function
import numpy as np

## Linear System of Equations
In Numpy there are a couple of handy functions for [solving equations and inverting matrices](http://docs.scipy.org/doc/numpy/reference/routines.linalg.html#solving-equations-and-inverting-matrices). Suppose we have the following three linear equations and we want to solve for $x$, $y$ and $z$:

$$
2x + y - 3z = 12\\
x - 3y + z = 7\\
4x + y - 2z = 4
$$

In [3]:
# Solve the system of equations 
#   2x+ y−3z = 12
#    x−3y+ z = 7
#   4x+ y−2z = 4

a = np.matrix([[2, 1, -3], [1, -3, 1], [4, 1, -2]])
b = np.matrix([[12], [7], [4]])

print(a)

[[ 2  1 -3]
 [ 1 -3  1]
 [ 4  1 -2]]


In [4]:
# We can solve by taking the inverse of matrix a times b
a.I * b

matrix([[-0.91304348],
        [-4.69565217],
        [-6.17391304]])

In [5]:
# A Faster and more stable way of doing the same is
# using the solve function
s = np.linalg.solve(a, b)
s

matrix([[-0.91304348],
        [-4.69565217],
        [-6.17391304]])

In [6]:
# Check the solution
x = s[0]
y = s[1]
z = s[2]

print(2*x +   y - 3*z)
print(  x - 3*y +   z)
print(4*x +   y - 2*z)

[[12.]]
[[7.]]
[[4.]]


In [7]:
# Check the solution by taking the dot product
np.allclose(np.dot(a, s), b)

True