In [1]:
import numpy as np

In [2]:
# input data

X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = np.array([[0,1,1,0]]).T

In [16]:
class NeuralNetwork():
    
    def __init__(self, X, y):
        
        self.X = X
        self.y = y
        self.num_features = len(X[0])
        self.num_outputs = len(y[0])
        self.layer1_neurons = 4
        self.weights_layer1 = 2*np.random.random((self.num_features, self.layer1_neurons))-1
        self.weights_layer2 = 2*np.random.random((self.layer1_neurons, self.num_outputs))-1
        
    
    def sigmoid(self, weighted_input):
        
        return 1/(1+np.exp(-weighted_input))
    
    
    def sigmoid_derivative(self, sigmoid_output):
        
        return sigmoid_output*(1-sigmoid_output)
        
    def train(self, num_epochs):
        
        for i in range(num_epochs):
            
            inputs = self.X
            
            layer1_pred = self.sigmoid(np.dot(inputs, self.weights_layer1))
            layer2_pred = self.sigmoid(np.dot(layer1_pred, self.weights_layer2))
            
            layer2_error = self.y - layer2_pred
            
            
            if (i%10000)==0:
                print("Error:", str(np.mean(np.abs(layer2_error))))
            
            #error weighted derivative
            
            
            layer2_delta = layer2_error * self.sigmoid_derivative(layer2_pred)
            layer2_gradient = np.dot(layer1_pred.T, layer2_delta)
            
            

            layer1_error = np.dot(layer2_delta, self.weights_layer2.T)
            
            layer1_delta = layer1_error * self.sigmoid_derivative(layer1_pred)
            layer1_gradient = np.dot(self.X.T, layer1_delta)
            
            self.weights_layer2 += layer2_gradient
            self.weights_layer1 += layer1_gradient
            
    def predict(self, new):
        
        layer1 = self.sigmoid(np.dot(new, self.weights_layer1))
        layer2 = self.sigmoid(np.dot(layer1, self.weights_layer2))
        return layer2
        
        

In [17]:
nn = NeuralNetwork(X,y)

In [18]:
nn.train(60000)

Error: 0.49950888573
Error: 0.0103658560397
Error: 0.00712247674104
Error: 0.00573721700728
Error: 0.00492574632641
Error: 0.00437802833652


In [19]:
nn.weights_layer1

array([[ 3.10305519,  6.95274936, -1.71962941,  6.01202485],
       [ 3.20695157, -5.85911077, -0.4274608 , -7.05283504],
       [-0.30390163,  2.8371537 ,  1.20254648, -2.96409346]])

In [20]:
nn.weights_layer2

array([[  4.41290193],
       [-10.90150095],
       [  2.64079937],
       [ 11.80037003]])

In [21]:
nn.predict([[0,1,1]])

array([[ 0.995871]])

In [22]:
nn.predict([1,1,0])

array([ 0.40011306])